name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create temp serviceAccount.json
        run: echo "{}" > serviceAccount.json
      - run: npm ci
      - run: npm run build
      - uses: w9jds/firebase-action@v13.7.5
        with:
          args: deploy --debug
        env:
          # See docs/tutorials/04-deploy.md for configuring these
          PROJECT_ID: devfest-milano-2024
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOVERBOARD_MASTER }}
